d <- read.csv("household_power_consumption.txt",sep=";",stringsAsFactors=FALSE)
dt<-subset(d, d$Date == "1/2/2007"| d$Date == "2/2/2007")
dt1 <- data.frame( datetime=paste(dt$Date,dt$Time,sep=" "), Global_active_power=as.numeric(dt$Global_active_power) , order(dt$Date,dt$Time) )
png(filename = "plot2.png",width = 480, height = 480)
plot(dt1$order.dt.Date..dt.Time.,dt$Global_active_power,type='l',axes=FALSE,ylab="Global Active Power (Kilowatts)",xlab="")
axis(1, at=c(1,1441,2881), lab=c("Thu","Fri","Sat"))
axis(2, at=c(0,2,4,6,8,10), lab=c("0","2","4","6","8","10"))
box()
dev.off()